# Generated by Django 5.1.11 on 2025-07-15 18:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFormsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='google_forms_templates/')),
            ],
        ),
        migrations.CreateModel(
            name='SeminarGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('lead', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discord_role_id', models.CharField(blank=True, max_length=128, null=True)),
                ('discord_channel_id', models.CharField(blank=True, max_length=128, null=True)),
                ('discord_voice_channel_id', models.CharField(blank=True, max_length=128, null=True)),
                ('default_difficulty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.DurationField()),
                ('discord_channel_id', models.CharField(blank=True, max_length=128, null=True)),
                ('discord_voice_channel_id', models.CharField(blank=True, max_length=128, null=True)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('difficulty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('featured', models.BooleanField(default=False)),
                ('special_guest', models.BooleanField(default=False)),
                ('theme', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kolo_images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='kolo_files/')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seminars.googleformstemplate')),
                ('tutors', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seminars.seminargroup')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('date_time', models.DateTimeField()),
                ('pinged', models.BooleanField(default=False)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='seminars.seminar')),
            ],
            options={
                'indexes': [models.Index(fields=['date_time'], name='reminder_index')],
            },
        ),
        migrations.AddIndex(
            model_name='seminar',
            index=models.Index(fields=['date', 'time'], name='seminars_se_date_98d5d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='seminar',
            constraint=models.CheckConstraint(condition=models.Q(('started', True), ('finished', False), _connector='OR'), name='if_finished_then_started'),
        ),
    ]
