# Generated by Django 5.1.4 on 2025-01-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0007_seminargroup_discord_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='number_of_attenders',
            field=models.IntegerField(default=0),
        ),
    ]
