# Generated by Django 5.1.4 on 2025-01-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0008_seminar_number_of_attenders'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminargroup',
            name='discord_voice_channel_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
