# Generated by Django 5.1.11 on 2025-09-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0011_alter_seminar_form_reminder_reminder_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminargroup',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
