# Generated by Django 6.0.1 on 2026-04-24 01:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0011_alter_seminar_form_reminder_reminder_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('member_count', models.PositiveIntegerField(blank=True, help_text='Liczba członków na koniec edycji.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('member_count_is_estimate', models.BooleanField(default=True, help_text='Dodaje plus do liczby, np. 2000+.')),
                ('brochure', models.FileField(blank=True, help_text='Opcjonalny plik PDF z materiałami dla tej edycji.', upload_to='brochures/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='previous_edition_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='PreviousEditionMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('show_date', models.BooleanField(default=True, help_text='Odznacz, jeśli data ma być używana tylko do sortowania.', verbose_name='Pokazuj datę')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('material_icon', models.CharField(default='flag', help_text='Nazwa symbolu Material Icons, np. flag, emoji_events, school.', max_length=64)),
                ('link_url', models.CharField(blank=True, help_text='Opcjonalny link.', max_length=500, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='seminars.previousedition')),
            ],
            options={
                'verbose_name': 'kamień milowy',
                'verbose_name_plural': 'kamienie milowe',
                'ordering': ['date', 'id'],
            },
        ),
    ]
