# Generated by Django 6.0.7 on 2026-07-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0012_previousedition_previouseditionmilestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previouseditionmilestone',
            name='link_url',
            field=models.CharField(blank=True, help_text='Opcjonalny link. Dozwolone są pełne adresy http(s)://... oraz ścieżki w obrębie strony, np. /about/.', max_length=500),
        ),
    ]
