# Generated by Django 6.0.7 on 2026-08-01 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0013_fix_milestone_link_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminargroup',
            name='color',
            field=models.CharField(blank=True, help_text='Kolor w formacie #RRGGBB. Pozostaw puste, aby użyć koloru domyślnego.', max_length=7, validators=[django.core.validators.RegexValidator(message='Podaj kolor w formacie szesnastkowym, np. #F24535.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='seminargroup',
            name='short_label',
            field=models.CharField(blank=True, help_text='Krótka etykieta używana w filtrach kalendarza, np. „OM śr.”. Domyślnie pełna nazwa.', max_length=32),
        ),
    ]
