# Generated by Django 5.1.11 on 2025-07-15 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='post_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('content', models.TextField(blank=True, max_length=5000)),
                ('file', models.FileField(blank=True, upload_to='post_files/')),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, to='mainSite.image')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'time'], name='mainSite_po_date_f901e1_idx')],
            },
        ),
    ]
