# Generated by Django 5.1.11 on 2025-09-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0006_remove_post_mainsite_po_date_dc489a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('badge', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=2000)),
                ('date', models.DateField()),
            ],
        ),
    ]
