# Generated by Django 6.0.1 on 2026-03-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0006_remove_post_mainsite_po_date_dc489a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('registration_begin', models.DateField()),
                ('registration_end', models.DateField()),
                ('registration_url', models.URLField(max_length=500)),
            ],
        ),
    ]
