# Generated by Django 5.1.12 on 2025-09-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0006_remove_post_mainsite_po_date_dc489a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
