# Generated by Django 6.0.7 on 2026-08-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0007_registrationevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa widoczna dla czytników ekranu.', max_length=200)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('url', models.URLField(blank=True, help_text='Opcjonalny link do strony partnera.', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Mniejsza wartość - wcześniej na liście.')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partnerzy',
                'ordering': ['order', 'name'],
            },
        ),
    ]
