# Generated by Django 6.0.7 on 2026-08-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0008_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationevent',
            name='image',
            field=models.ImageField(blank=True, help_text='Format WebP. Proporcje 16:9 (np. 1600×900 px), minimum 1200×675 px, do 400 kB. Kadr wypełnia całą szerokość kafelka, więc najważniejsze elementy trzymaj z dala od krawędzi. Puste pole = zdjęcie domyślne.', upload_to='events/', verbose_name='zdjęcie'),
        ),
    ]
