# Generated by Django 6.0.7 on 2026-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0009_registrationevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationevent',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Odznacz, aby ukryć wydarzenie w kalendarzu i w API.'),
        ),
    ]
