# Generated by Django 6.0.7 on 2026-08-21 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0010_registrationevent_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60, unique=True, verbose_name='napis')),
                ('color', models.CharField(choices=[('executive', 'zarząd'), ('normal', 'zwykła'), ('award', 'osiągnięcie')], default='normal', max_length=16, verbose_name='kolor')),
                ('icon', models.CharField(blank=True, help_text='Nazwa ikony Material Symbols. Puste pole = ikona domyślna dla koloru.', max_length=50, verbose_name='ikona')),
                ('order', models.PositiveIntegerField(default=0, help_text='Mniejsza wartość - wcześniej, na każdej wizytówce tak samo.', verbose_name='kolejność')),
            ],
            options={
                'verbose_name': 'plakietka',
                'verbose_name_plural': 'plakietki',
                'ordering': ['order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000, verbose_name='opis')),
                ('image', models.ImageField(blank=True, help_text='Dowolny format i rozmiar - zdjęcie zostanie przekonwertowane na WebP i przycięte do 600x400 px. Puste pole = ikona zamiast portretu.', upload_to='bios/', verbose_name='zdjęcie')),
                ('order', models.PositiveIntegerField(default=0, help_text='Mniejsza wartość - wcześniej na stronie.', verbose_name='kolejność')),
                ('is_published', models.BooleanField(default=True, help_text='Odznacz, aby ukryć wizytówkę na stronie „Kim jesteśmy?”.', verbose_name='opublikowana')),
                ('badges', models.ManyToManyField(blank=True, related_name='bios', to='mainSite.badge', verbose_name='plakietki')),
                ('user', models.OneToOneField(help_text='Imię i nazwisko na wizytówce pochodzą z tego konta.', on_delete=django.db.models.deletion.CASCADE, related_name='bio', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'wizytówka',
                'verbose_name_plural': 'wizytówki',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
