# Generated by Django 6.0.7 on 2026-08-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0012_about_bios'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='badge',
            field=models.CharField(blank=True, help_text='Poziom współpracy, pokazany nad logo. Puste pole = bez plakietki.', max_length=40, verbose_name='plakietka'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Żółta plakietka zamiast turkusowej i żółta ramka wokół logo.', verbose_name='wyróżniony'),
        ),
    ]
