# Generated by Django 6.0.7 on 2026-08-01 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(help_text='Skrót używany na pasku w kalendarzu, np. OM.', max_length=32)),
                ('logo', models.ImageField(blank=True, help_text='Logo wyświetlane przy etapach olimpiady w kalendarzu.', upload_to='olympiad_logos/')),
                ('website_url', models.URLField(blank=True, help_text='Strona olimpiady, używana dla etapów bez własnego odnośnika.', max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Kolejność wyświetlania w kalendarzu (rosnąco).')),
                ('is_active', models.BooleanField(default=True, help_text='Odznacz, aby ukryć etapy tej olimpiady w kalendarzu.')),
            ],
            options={
                'verbose_name': 'olimpiada',
                'verbose_name_plural': 'olimpiady',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='II etap', help_text='Nazwa etapu wyświetlana w kalendarzu, np. „II etap” albo „Finał”.', max_length=64)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('location', models.CharField(blank=True, max_length=128)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='olympiads.olympiad')),
            ],
            options={
                'verbose_name': 'etap olimpiady',
                'verbose_name_plural': 'etapy olimpiad',
                'ordering': ['date_begin', 'olympiad__order', 'olympiad__name'],
                'indexes': [models.Index(fields=['date_begin', 'date_end'], name='olympiads_o_date_be_9b945a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_end__gte', models.F('date_begin'))), name='olympiad_stage_end_after_begin'), models.UniqueConstraint(fields=('olympiad', 'name', 'date_begin'), name='olympiad_stage_unique_per_start')],
            },
        ),
    ]
