# Generated by Django 6.0.7 on 2026-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0002_default_olympiads'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiadstage',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Odznacz, aby ukryć ten etap w kalendarzu i w API.'),
        ),
    ]
