"""
Django settings for mikosite project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from babel import Locale

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

try:
    # Used for securing signed data, must be protected
    from .secrets import SECRET_KEY
except ImportError:
    raise ImportError("Create a secrets.py file with the SECRET_KEY.")

CSRF_TRUSTED_ORIGINS = [
    'https://mikomath.org',
    'http://mikomath.org',
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 1209600  # 2 weeks, in seconds
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ALLOWED_HOSTS = [
    "mikomath.org",
    "127.0.0.1",
    "localhost",
]
APPEND_SLASH = True

# Application definition

INSTALLED_APPS = [
    "accounts",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'more_admin_filters',
    'rangefilter',
    "mainSite",
    "hintBase",
    "taggit",
    "formtools",
    "seminars",
    "olympiads",
    "cards",
    # After the local apps, so their template overrides win.
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.discord",
]
if DEBUG:
    INSTALLED_APPS = ['debug_toolbar'] + INSTALLED_APPS

INTERNAL_IPS = [
    "127.0.0.1",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # For browser-based access
        'rest_framework.authentication.TokenAuthentication',    # For API access with tokens
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'mikosite.permissions.IsAdmin',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'mikosite.throttling.SessionUserThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'session_user': '1440/day',
    },
    'DEFAULT_PAGINATION_CLASS': 'mikosite.pagination.CustomLimitOffsetPagination',
    'PAGE_SIZE': 30,
}

USE_L10N = True
TAGGIT_CASE_INSENSITIVE = True

MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if DEBUG:
    MIDDLEWARE = ['debug_toolbar.middleware.DebugToolbarMiddleware'] + MIDDLEWARE

ROOT_URLCONF = 'mikosite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.turnstile_keys',
            ],
        },
    },
]

WSGI_APPLICATION = 'mikosite.wsgi.application'

sqlite_db_path = BASE_DIR / 'db.sqlite3'

if sqlite_db_path.exists():
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_db_path,
        }
    }
else:
    try:
        from .secrets import DB_PASSWORD
    except ImportError:
        raise ImportError("You must create a SQLite db or provide the Postgres password in secrets.py as DB_PASSWORD.")

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'mikodb',
            'USER': 'mikouser',
            'PASSWORD': DB_PASSWORD,
            'HOST': os.getenv('DB_HOST', 'postgres'),
            'PORT': '5432',
            'OPTIONS': {
                'pool': {
                    'min_size': 2,
                    'max_size': 4,
                    'timeout': 10,
                }
            }
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 10}},
    {"NAME": "accounts.validators.UpperDigitSpecialValidator", "OPTIONS": {"min_upper": 1, "min_digits": 1, "min_special": 1}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
]

USE_REDIS_WITH_DEBUG = False
if not DEBUG or USE_REDIS_WITH_DEBUG:
    REDIS_HOST = os.getenv('REDIS_HOST', 'redis')
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": f"redis://{REDIS_HOST}:6379/1",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {"max_connections": 8},
            },
        }
    }

    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    CACHE_BACKEND = f'redis_cache.cache://{REDIS_HOST}:6379/1'
    SESSION_CACHE_ALIAS = "default"

# Parallel test workers get a database each but would share one Redis, so cached
# payloads - and cache.clear() - leak between them. An in-process cache is private
# to each worker.
if 'test' in sys.argv:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pl-pl'
BABEL_LOCALE = Locale('pl_PL')

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
COMPRESS_OFFLINE = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"
MIN_USERNAME_LENGTH = 4
MAX_USERNAME_LENGTH = 32
MIN_AGE_YEARS = 13

try:
    from .secrets import TURNSTILE_SITE_KEY, TURNSTILE_SECRET_KEY
except ImportError:
    print("Turnstile details not found in secrets.py, falling back to env variables.")
    TURNSTILE_SITE_KEY = os.getenv("TURNSTILE_SITE_KEY", "")
    TURNSTILE_SECRET_KEY = os.getenv("TURNSTILE_SECRET_KEY", "")

# --------------------------------------------------------------------------- #
# Accounts: allauth flows, email delivery, OAuth providers
# --------------------------------------------------------------------------- #

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

ACCOUNT_ADAPTER = 'accounts.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.SocialAccountAdapter'

ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']
ACCOUNT_USERNAME_MIN_LENGTH = MIN_USERNAME_LENGTH
# Provider-verified emails (Google, Discord) arrive confirmed and skip the mail.
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[MIKO] '
ACCOUNT_EMAIL_NOTIFICATIONS = True  # notify on password change etc.
ACCOUNT_CHANGE_EMAIL = True  # one address per account, replaced only after confirmation
ACCOUNT_SESSION_REMEMBER = True  # sessions persist, as they always have here
ACCOUNT_REAUTHENTICATION_REQUIRED = True  # linking/unlinking asks for a fresh login

# Region and date of birth are required model fields no provider supplies, so
# every social signup must pass through the completion form that asks for them.
SOCIALACCOUNT_AUTO_SIGNUP = False

# Skip allauth's "Continue" interstitial. Its CSRF concern stays covered:
# connecting still demands reauthentication, and a forced login redirect only
# reaches the visitor's own provider consent screen.
SOCIALACCOUNT_LOGIN_ON_GET = True

ACCOUNT_SIGNUP_FORM_CLASS = 'accounts.signup_extras.SignupExtrasForm'
ACCOUNT_FORMS = {
    'login': 'accounts.forms.HouseLoginForm',
    'signup': 'accounts.forms.TurnstileSignupForm',
    'change_password': 'accounts.forms.HouseChangePasswordForm',
    'set_password': 'accounts.forms.HouseSetPasswordForm',
    'reset_password': 'accounts.forms.TurnstileResetPasswordForm',
    'reset_password_from_key': 'accounts.forms.HouseResetPasswordKeyForm',
}

ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http' if DEBUG else 'https'

# The Workspace relay only accepts mail from the production IP; development
# writes each message to a file under dev-emails/ instead.
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    EMAIL_FILE_PATH = BASE_DIR / 'dev-emails'
else:
    EMAIL_HOST = 'smtp-relay.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_TIMEOUT = 10  # never let a worker hang on SMTP
DEFAULT_FROM_EMAIL = 'MIKO <no-reply@mikomath.org>'

try:
    from .secrets import GOOGLE_OAUTH_CLIENT_ID, GOOGLE_OAUTH_CLIENT_SECRET
except ImportError:
    GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID", "")
    GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", "")

try:
    from .secrets import DISCORD_OAUTH_CLIENT_ID, DISCORD_OAUTH_CLIENT_SECRET
except ImportError:
    DISCORD_OAUTH_CLIENT_ID = os.getenv("DISCORD_OAUTH_CLIENT_ID", "")
    DISCORD_OAUTH_CLIENT_SECRET = os.getenv("DISCORD_OAUTH_CLIENT_SECRET", "")

# A provider without credentials configures no app and renders no button.
SOCIALACCOUNT_PROVIDERS = {}
if GOOGLE_OAUTH_CLIENT_ID:
    SOCIALACCOUNT_PROVIDERS['google'] = {
        'APPS': [{'client_id': GOOGLE_OAUTH_CLIENT_ID, 'secret': GOOGLE_OAUTH_CLIENT_SECRET}],
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
if DISCORD_OAUTH_CLIENT_ID:
    SOCIALACCOUNT_PROVIDERS['discord'] = {
        'APPS': [{'client_id': DISCORD_OAUTH_CLIENT_ID, 'secret': DISCORD_OAUTH_CLIENT_SECRET}],
        'SCOPE': ['identify', 'email'],
    }

if not DEBUG:
    LOGS_DIR = BASE_DIR / "logs"
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    ERROR_LOG_FILE = LOGS_DIR / "django-errors.log"

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
            }
        },
        "handlers": {
            "error_file": {
                "class": "logging.FileHandler",
                "level": "ERROR",
                "filename": str(ERROR_LOG_FILE),
                "formatter": "verbose",
            }
        },
        "loggers": {
            "django": {
                "handlers": ["error_file"],
                "level": "ERROR",
                "propagate": False,
            },
            "django.request": {
                "handlers": ["error_file"],
                "level": "ERROR",
                "propagate": False,
            },
            "django.server": {
                "handlers": ["error_file"],
                "level": "ERROR",
                "propagate": False,
            },
        },
        "root": {
            "handlers": ["error_file"],
            "level": "ERROR",
        },
    }
