# Generated by Django 5.1.11 on 2025-07-15 18:00

import accounts.validators
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the user, automatically generated.', primary_key=True, serialize=False, verbose_name='Unique User ID')),
                ('region', models.CharField(choices=[('DS', 'Dolnośląskie'), ('KP', 'Kujawsko-Pomorskie'), ('LB', 'Lubelskie'), ('LS', 'Lubuskie'), ('LD', 'Łódzkie'), ('ML', 'Małopolskie'), ('MZ', 'Mazowieckie'), ('OP', 'Opolskie'), ('PK', 'Podkarpackie'), ('PL', 'Podlaskie'), ('PM', 'Pomorskie'), ('SL', 'Śląskie'), ('SK', 'Świętokrzyskie'), ('WM', 'Warmińsko-Mazurskie'), ('WP', 'Wielkopolskie'), ('ZP', 'Zachodniopomorskie'), ('NS', 'Nieznany')], help_text="Select the user's region", max_length=2, verbose_name='Region')),
                ('date_of_birth', models.DateField(help_text="Enter the user's date of birth (YYYY-MM-DD).", validators=[accounts.validators.validate_not_future_date, accounts.validators.validate_min_age_13], verbose_name='Date of Birth')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/profile_images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], include=('change',), name='activity_score_index')],
            },
        ),
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=128)),
                ('platform', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('external_id', 'platform'), ('user', 'platform')},
            },
        ),
    ]
