# Generated by Django 5.1.4 on 2025-01-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_linkedaccount_accounts_li_externa_ed775c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=18, unique=True)),
                ('nick', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='discord_account',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
