# Generated by Django 5.1.3 on 2024-12-27 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_date_of_birth_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'required': 'To pole nie może być puste.', 'unique': 'Użytkownik o tej nazwie już istnieje.'}, max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
