# Generated by Django 5.1.3 on 2025-12-31 12:35

import accounts.validators
import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_options_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 12, 31), validators=[accounts.validators.ValidateMinAge(13)], verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique User ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('DS', 'dolnośląskie'), ('KP', 'kujawsko-pomorskie'), ('LU', 'lubelskie'), ('LB', 'lubuskie'), ('LD', 'łódzkie'), ('MA', 'małopolskie'), ('MZ', 'mazowieckie'), ('OP', 'opolskie'), ('PK', 'podkarpackie'), ('PD', 'podlaskie'), ('PM', 'pomorskie'), ('SL', 'śląskie'), ('SK', 'świętokrzyskie'), ('WN', 'warmińsko-mazurskie'), ('WP', 'wielkopolskie'), ('ZP', 'zachodniopomorskie'), ('NA', 'nieznany')], max_length=2, verbose_name='Region'),
        ),
    ]
