# Generated by Django 6.0.7 on 2026-08-18 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_allauth_baseline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkedAccount',
        ),
    ]
